export interface QuickPickCountry {
  name: string;
  code: string;
  flag: string;
  capital: string;
  region: "Europe" | "Asia" | "Americas" | "Middle East";
  visaStatus: "Citizen" | "Visa Free" | "Visa on Arrival" | "eVisa" | "Visa Required";
  visaDuration?: string;
  visaNote: string;
}

export const QUICK_PICK_COUNTRIES: QuickPickCountry[] = [
  {
    name: "India",
    code: "IN",
    flag: "🇮🇳",
    capital: "New Delhi",
    region: "Asia",
    visaStatus: "eVisa",
    visaDuration: "30 - 365 Days",
    visaNote: "Digital e-Tourist Visa available online for most international travelers via the official portal.",
  },
  {
    name: "UAE",
    code: "AE",
    flag: "🇦🇪",
    capital: "Abu Dhabi",
    region: "Middle East",
    visaStatus: "Visa on Arrival",
    visaDuration: "14 - 30 Days",
    visaNote: "VOA available for select nationalities or travelers with valid US/UK/EU visas; otherwise pre-arranged tourist eVisa.",
  },
  {
    name: "Thailand",
    code: "TH",
    flag: "🇹🇭",
    capital: "Bangkok",
    region: "Asia",
    visaStatus: "Visa Free",
    visaDuration: "60 Days",
    visaNote: "Visa exemption or VOA available for eligible international tourists for up to 60 days. Return ticket & proof of funds required.",
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "🇸🇬",
    capital: "Singapore",
    region: "Asia",
    visaStatus: "eVisa",
    visaDuration: "30 Days",
    visaNote: "Must apply for an entry visa via authorized agents and submit SG Arrival Card within 3 days before departure.",
  },
  {
    name: "Malaysia",
    code: "MY",
    flag: "🇲🇾",
    capital: "Kuala Lumpur",
    region: "Asia",
    visaStatus: "Visa Free",
    visaDuration: "30 Days",
    visaNote: "Visa-free entry or eVisa available for most international visitors. Complete digital Malaysia Arrival Card (MDAC) prior to travel.",
  },
  {
    name: "Indonesia",
    code: "ID",
    flag: "🇮🇩",
    capital: "Jakarta",
    region: "Asia",
    visaStatus: "Visa on Arrival",
    visaDuration: "30 Days",
    visaNote: "Electronic Visa on Arrival (e-VOA) or VOA at airport for 30 days (extendable once). Fee: ~500,000 IDR.",
  },
  {
    name: "Vietnam",
    code: "VN",
    flag: "🇻🇳",
    capital: "Hanoi",
    region: "Asia",
    visaStatus: "eVisa",
    visaDuration: "30 - 90 Days",
    visaNote: "Official 90-day multi-entry or 30-day single-entry online eVisa issued via Vietnam immigration portal.",
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
    capital: "London",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 6 Months",
    visaNote: "Standard Visitor Visa application required via VFS Global with biometrics and financial documentation.",
  },
  {
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    capital: "Tokyo",
    region: "Asia",
    visaStatus: "eVisa",
    visaDuration: "90 Days",
    visaNote: "Single-entry short-term tourist eVisa or visa exemption available depending on passport nationality.",
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
    capital: "Bern",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "Schengen short-stay visa required. Apply via VFS Switzerland at least 3 weeks before departure.",
  },
  {
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    capital: "Paris",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "Schengen Visa (Type C) required for non-exempt passport holders. Apply via France-Visas & VFS Global.",
  },
  {
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    capital: "Washington DC",
    region: "Americas",
    visaStatus: "Visa Required",
    visaDuration: "10 Years (Multi-entry)",
    visaNote: "B1/B2 tourist visa required. Requires DS-160 application, biometric appointment, and consulate interview.",
  },
  {
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    capital: "Canberra",
    region: "Asia",
    visaStatus: "eVisa",
    visaDuration: "3 - 12 Months",
    visaNote: "Subclass 600 Visitor Visa applied online via ImmiAccount. No physical passport stamp required.",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "🇸🇦",
    capital: "Riyadh",
    region: "Middle East",
    visaStatus: "eVisa",
    visaDuration: "90 Days",
    visaNote: "Instant tourist eVisa / Visa on Arrival if holding active US, UK, or Schengen visa; otherwise tourist visa.",
  },
  {
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    capital: "Berlin",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "Schengen Visa required. Apply via VFS Germany with proof of accommodation, return flight, and travel insurance.",
  },
  {
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    capital: "Rome",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "Schengen Visa required. Apply via VFS Italy with complete travel itinerary and financial statements.",
  },
  {
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    capital: "Madrid",
    region: "Europe",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "Schengen Visa required via BLS International. Medical travel insurance with €30,000 cover mandatory.",
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    capital: "Seoul",
    region: "Asia",
    visaStatus: "Visa Required",
    visaDuration: "Up to 90 Days",
    visaNote: "C-3-9 tourist visa required via Korea Visa Application Center (KVAC). Visa-free transit for select corridors.",
  },
];

/**
 * Look up international passport and visa guidance for any country
 */
export function getPassportVisaGuidance(countryName: string, countryCode?: string): {
  status: "Citizen" | "Visa Free" | "Visa on Arrival" | "eVisa" | "Visa Required";
  duration?: string;
  note: string;
} {
  const normName = countryName.toLowerCase().trim();
  const normCode = (countryCode || "").toUpperCase().trim();

  const found = QUICK_PICK_COUNTRIES.find(
    (c) => c.name.toLowerCase() === normName || c.code === normCode
  );

  if (found) {
    return {
      status: found.visaStatus,
      duration: found.visaDuration,
      note: found.visaNote,
    };
  }

  return {
    status: "Visa Required",
    duration: "Varies",
    note: "Consult official consulate or embassy portal for nationality-specific passport entry requirements prior to departure.",
  };
}

// Retain backward-compatible alias
export const getIndianPassportVisaGuidance = getPassportVisaGuidance;

/**
 * Full expansion names for international alliances, intergovernmental organizations, and treaties
 */
export const ALLIANCE_FULL_NAMES: Record<string, string> = {
  UN: "United Nations",
  EU: "European Union",
  NATO: "North Atlantic Treaty Organization",
  G7: "Group of Seven (Major Advanced Economies)",
  G20: "Group of Twenty (Major Advanced & Emerging Economies)",
  BRICS: "Brazil, Russia, India, China, South Africa & Partner Nations",
  COMMONWEALTH: "Commonwealth of Nations",
  ASEAN: "Association of Southeast Asian Nations",
  OPEC: "Organization of the Petroleum Exporting Countries",
  OECD: "Organisation for Economic Co-operation and Development",
  WTO: "World Trade Organization",
  WHO: "World Health Organization",
  IMF: "International Monetary Fund",
  "WORLD BANK": "World Bank Group",
  MERCOSUR: "Southern Common Market (Mercado Común del Sur)",
  "AFRICAN UNION": "African Union (AU)",
  "ARAB LEAGUE": "League of Arab States",
  USMCA: "United States–Mexico–Canada Agreement",
  NAFTA: "North American Free Trade Agreement",
  CARICOM: "Caribbean Community",
  "NORDIC COUNCIL": "Nordic Council of Ministers",
  APEC: "Asia-Pacific Economic Cooperation",
  SCO: "Shanghai Cooperation Organisation",
  SAARC: "South Asian Association for Regional Cooperation",
  BIMSTEC: "Bay of Bengal Initiative for Multi-Sectoral Technical & Economic Cooperation",
  INTERPOL: "International Criminal Police Organization",
  OAS: "Organization of American States",
  SADC: "Southern African Development Community",
  ECOWAS: "Economic Community of West African States",
  EAC: "East African Community",
  GCC: "Gulf Cooperation Council",
  EFTA: "European Free Trade Association",
  CEFTA: "Central European Free Trade Agreement",
  "COUNCIL OF EUROPE": "Council of Europe",
  OSCE: "Organization for Security and Co-operation in Europe",
  QUAD: "Quadrilateral Security Dialogue (Australia, India, Japan, US)",
  AUKUS: "Australia, United Kingdom, United States Trilateral Partnership",
  CPTPP: "Comprehensive & Progressive Agreement for Trans-Pacific Partnership",
  RCEP: "Regional Comprehensive Economic Partnership",
  CICA: "Conference on Interaction and Confidence-Building Measures in Asia",
};

/**
 * Common ISO-3 Country Code to Full Country Name mappings for bordering nation badges
 */
export const BORDER_COUNTRY_NAMES: Record<string, string> = {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algeria",
  AND: "Andorra",
  AGO: "Angola",
  ARG: "Argentina",
  ARM: "Armenia",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BLR: "Belarus",
  BEL: "Belgium",
  BLZ: "Belize",
  BEN: "Benin",
  BTN: "Bhutan",
  BOL: "Bolivia",
  BIH: "Bosnia and Herzegovina",
  BWA: "Botswana",
  BRA: "Brazil",
  BRN: "Brunei",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  KHM: "Cambodia",
  CMR: "Cameroon",
  CAN: "Canada",
  CAF: "Central African Republic",
  TCD: "Chad",
  CHL: "Chile",
  CHN: "China",
  COL: "Colombia",
  CRI: "Costa Rica",
  HRV: "Croatia",
  CUB: "Cuba",
  CYP: "Cyprus",
  CZE: "Czech Republic",
  DNK: "Denmark",
  DJI: "Djibouti",
  DOM: "Dominican Republic",
  ECU: "Ecuador",
  EGY: "Egypt",
  SLV: "El Salvador",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  EST: "Estonia",
  ETH: "Ethiopia",
  FIN: "Finland",
  FRA: "France",
  GAB: "Gabon",
  GMB: "Gambia",
  GEO: "Georgia",
  DEU: "Germany",
  GHA: "Ghana",
  GRC: "Greece",
  GTM: "Guatemala",
  GIN: "Guinea",
  GUY: "Guyana",
  HTI: "Haiti",
  HND: "Honduras",
  HUN: "Hungary",
  ISL: "Iceland",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Iran",
  IRQ: "Iraq",
  IRL: "Ireland",
  ISR: "Israel",
  ITA: "Italy",
  CIV: "Ivory Coast",
  JAM: "Jamaica",
  JPN: "Japan",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KWT: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Laos",
  LVA: "Latvia",
  LBN: "Lebanon",
  LBR: "Liberia",
  LBY: "Libya",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MDG: "Madagascar",
  MWI: "Malawi",
  MYS: "Malaysia",
  MDV: "Maldives",
  MLI: "Mali",
  MLT: "Malta",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MEX: "Mexico",
  MDA: "Moldova",
  MCO: "Monaco",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NPL: "Nepal",
  NLD: "Netherlands",
  NZL: "New Zealand",
  NIC: "Nicaragua",
  NER: "Niger",
  NGA: "Nigeria",
  PRK: "North Korea",
  MKD: "North Macedonia",
  NOR: "Norway",
  OMN: "Oman",
  PAK: "Pakistan",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PHL: "Philippines",
  POL: "Poland",
  PRT: "Portugal",
  QAT: "Qatar",
  ROU: "Romania",
  RUS: "Russia",
  RWA: "Rwanda",
  SAU: "Saudi Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SLE: "Sierra Leone",
  SGP: "Singapore",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SOM: "Somalia",
  ZAF: "South Africa",
  KOR: "South Korea",
  SSD: "South Sudan",
  ESP: "Spain",
  LKA: "Sri Lanka",
  SDN: "Sudan",
  SUR: "Suriname",
  SWE: "Sweden",
  CHE: "Switzerland",
  SYR: "Syria",
  TWN: "Taiwan",
  TJK: "Tajikistan",
  TZA: "Tanzania",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TGO: "Togo",
  TUN: "Tunisia",
  TUR: "Turkey",
  TKM: "Turkmenistan",
  UGA: "Uganda",
  UKR: "Ukraine",
  ARE: "United Arab Emirates",
  GBR: "United Kingdom",
  USA: "United States",
  URY: "Uruguay",
  UZB: "Uzbekistan",
  VEN: "Venezuela",
  VNM: "Vietnam",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
};
